apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: win
  namespace: win
spec:
  amiFamily: Windows2019
  role: Karpenter-test-kube-prometheus
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: test-kube-prometheus
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: test-kube-prometheus
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        iops: 10000
        deleteOnTermination: true
        throughput: 125   
  tags:
    Test: test-kube-prometheus
    NodeGroup: win
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: win
  namespace: win
spec:
  template:
    metadata:
      labels:
        nodegroup: "win"
    spec:
      nodeClassRef:
        name: win
      taints:
        - key: type
          value: win
          effect: NoSchedule
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]  
  limits:
    cpu: 1000
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s